import time
timespank=time.strftime("%H:%M:%S")
print(timespank)
timespank=time.strftime("%H")
print(timespank)
timespank=time.strftime("%M")
print(timespank)
timespank=time.strftime("%S")
print(timespank)
timespank=time.strftime("%a:%m:%Y")
print(timespank)
timespank=time.strftime("%A:%m:%Y")
print(timespank)
timespank=time.strftime("%I : %p :%S")
print("I P S :",timespank)
timespank=time.strftime("%j")
print(timespank)
timespank=time.strftime("%B : %d :%D")
print("B d D ",timespank)
timespank=time.strftime("%A :%B :%d ")
print(timespank)