str="manjeet !!!!"
print("uper",str.upper())
str2="RAJ is a good boy"
print("lower:",str.lower())
print("rstrip:",str.rstrip("!"))
print("capital:",str.capitalize())
print("count:",str.count("e"))
print("replace:",str.replace("manjeet","Arjun"))
print("length:",len(str))
print("endswith: ",str.endswith("!"))
print("startswith: ",str.startswith("m"))
print("find: ",str.find("e"))
print("index:",str.index("e"))
print("isalnum:",str.isalnum())
print("isalpha:",str.isalpha())
print("islower: ",str.islower())
print("isupper: ",str.isupper())
print("isspace:",str.isspace())
print("tittle: ",str.title())
print("swapcase: ",str.swapcase())
print("istittele: ",str2.istitle())